parameters:
  qrcode.size: 400
  qrcode.margin: 10
  token_generator.secret_key: '%env(TOKEN_SECRET_KEY)%'
  token_generator.interval_duration: 300 # 5 minutes

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Service TokenGenerator
  App\Service\TokenGenerator:
    arguments:
      $secretKey: '%token_generator.secret_key%'
      $intervalDuration: '%token_generator.interval_duration%'

  # Configuration du QR Code Builder
  Endroid\QrCode\Builder\BuilderInterface:
    class: Endroid\QrCode\Builder\Builder
